### ISSUE TITLE
version number issue in package manager

### ISSUE THREAD

**Issue by b-r-hamilton** [ggebbie/UnitfulLinearAlgebra.jl#47]
This is probably just be me being silly, but when I check the status of my packages, it says that ULA is on v.0.1.0, but on Github it says it's version alpha.2.something. Am I missing something?

**Comment by ggebbie** [comment]
This is the expected behavior for how I set it up.

Julia reads the version number in the Project.toml which currently says v0.1.0. 

When checking into GitHub, I have made some "alpha" releases. 

The idea is to not increment the official Project.toml past v0.1.0 until the package is in the official Julia registry. Otherwise the Julia package tools complain about a package not starting at v0.1.0.

**Comment by b-r-hamilton** [comment]
got it, thanks!
